spring:
  application:
    name: weather-app
  data:
    mongodb:
      host: '${MONGO_HOST}'
      port: 27017
      database: admin
      username: '${MONGO_USERNAME}'
      password: '${MONGO_PASSWORD}'
  cloud:
    kubernetes:
      discovery:
        register: true
      secrets:
        name: mongodb-secret

      config:
        enabled: true
        sources:
          - namespace: default
            name: mongodb-configmap

management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
      show-details: always
    info:
      enabled: true